<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AdCodicem.Pdf.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="FsCheck" />
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AdCodicem.Pdf/AdCodicem.Pdf.csproj" />
    <ProjectReference Include="../AdCodicem.Pdf.TestSupport/AdCodicem.Pdf.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="AwesomeAssertions" />
    <Using Include="NSubstitute" />
    <Using Include="Xunit" />
    <Using Include="AdCodicem.Pdf.TestSupport" />
    <Using Include="AdCodicem.Pdf.TestSupport.AssertionHelpers" Static="true" />
  </ItemGroup>

</Project>
