using System.Globalization;
using System.Text;
using AdCodicem.Pdf.Validation.Arlington;

namespace AdCodicem.Pdf.Arlington;

/// <summary>
/// Writes the reduced model as <c>ArlingtonModel.g.cs</c>: static tables of bytes the compiler stores as data in the
/// assembly, read without a static constructor and without allocating, in the layout of
/// <see cref="ArlingtonLayout"/>.
/// </summary>
/// <remarks>
/// Each object, row, link and value is one line, under a comment naming it (<c>/* PageObject/MediaBox */</c>), so
/// that an update of the model reads row by row in a diff. Rows say how many links and values they have, not where
/// they start, so that one row's change does not move every line after it.
/// </remarks>
internal static class TableEmitter
{
    /// <summary>The objects the walk names, which the generated class gives constants for.</summary>
    public static readonly IReadOnlyList<string> WellKnownObjects =
        ["Catalog", "FileTrailer", "LinearizationParameterDict", "PageObject", "PageTreeNode", "PageTreeNodeRoot", "XRefStream"];

    /// <summary>Writes the tables, and refuses a model whose numbers do not fit them.</summary>
    public static string Emit(CompiledModel model)
    {
        ArgumentNullException.ThrowIfNull(model);
        var names = NameIds(model);
        var objectIds = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var i = 0; i < model.Objects.Count; i++)
        {
            objectIds.Add(model.Objects[i].Name, i);
        }

        Refuse(model.Objects.Count >= ArlingtonLayout.CandidateSetFlag, $"{model.Objects.Count} objects do not fit a link's 15 bits.");
        Refuse(model.CandidateSets.Count >= ArlingtonLayout.CandidateSetFlag, $"{model.CandidateSets.Count} candidate sets do not fit a link's 15 bits.");
        Refuse(names.Count >= ArlingtonLayout.NoPlan, $"{names.Count} names do not fit 16 bits.");

        var text = new StringBuilder();
        WriteHeader(text, model);
        WriteNames(text, names);
        WriteObjects(text, model);
        WriteRows(text, model, names);
        WriteLinks(text, model, objectIds);
        WriteCandidateSets(text, model, names, objectIds);
        WriteValues(text, model, names);
        WriteExtras(text, model);
        text.Append("}\n");
        return text.ToString();
    }

    private static List<string> NameIds(CompiledModel model)
    {
        // Objects first, so that an object's number is its name's; then every other key and value, in ordinal order.
        var others = new SortedSet<string>(StringComparer.Ordinal);
        var objects = new HashSet<string>(StringComparer.Ordinal);

        foreach (var obj in model.Objects)
        {
            objects.Add(obj.Name);
        }

        foreach (var obj in model.Objects)
        {
            foreach (var row in obj.Rows)
            {
                others.Add(row.Key);

                foreach (var value in row.Values)
                {
                    others.Add(value.Text);
                }
            }
        }

        others.ExceptWith(objects);
        return [.. model.Objects.Select(static o => o.Name), .. others];
    }

    private static void WriteHeader(StringBuilder text, CompiledModel model)
    {
        text.Append("// <auto-generated/>\n")
            .Append("// Generated by tools/AdCodicem.Pdf.Arlington from the Arlington PDF Model\n")
            .Append("// (https://github.com/pdf-association/arlington-pdf-model), commit ").Append(model.Commit).Append(", tsv/latest.\n")
            .Append("// The Arlington PDF Model is Copyright 2020 PDF Association, Inc., licensed under the Apache License, Version 2.0\n")
            .Append("// (tools/AdCodicem.Pdf.Arlington/model/LICENSE); NOTICE carries its notice.\n")
            .Append("// Changed: reduced to lookup tables and overridden as tools/AdCodicem.Pdf.Arlington/overrides.tsv records.\n")
            .Append("// Do not edit by hand. To regenerate: dotnet run --project tools/AdCodicem.Pdf.Arlington -- generate\n")
            .Append("// The tables' layout is ArlingtonLayout's, in ArlingtonEncoding.cs.\n")
            .Append('\n')
            .Append("namespace AdCodicem.Pdf.Validation.Arlington;\n")
            .Append('\n')
            .Append("internal static partial class ArlingtonModel\n")
            .Append("{\n");

        Constant(text, "The commit of the Arlington PDF Model the tables were generated from.", "string", "ModelCommit", $"\"{model.Commit}\"");
        Constant(text, "The number of objects the model describes.", "int", "ObjectCount", Number(model.Objects.Count));
        Constant(text, "The number of rows of all the objects together.", "int", "RowCount", Number(model.Objects.Sum(static o => o.Rows.Count)));
        Constant(text, "The number of distinct lists of more than one candidate the links name.", "int", "CandidateSetCount", Number(model.CandidateSets.Count));

        foreach (var name in WellKnownObjects)
        {
            var index = -1;

            for (var i = 0; i < model.Objects.Count && index < 0; i++)
            {
                if (model.Objects[i].Name == name)
                {
                    index = i;
                }
            }

            if (index >= 0)
            {
                Constant(text, $"The number of the object <c>{name}</c>.", "int", name, Number(index));
            }
        }
    }

    private static void Constant(StringBuilder text, string summary, string type, string name, string value) =>
        text.Append("    /// <summary>").Append(summary).Append("</summary>\n")
            .Append("    public const ").Append(type).Append(' ').Append(name).Append(" = ").Append(value).Append(";\n")
            .Append('\n');

    private static void WriteNames(StringBuilder text, List<string> names)
    {
        // One line per name, its bytes under a comment giving its number and text. Not UTF-8 literals joined by +:
        // the compiler takes seconds to fold two thousand of them (measured: 2.2 s against 0.2 s for these bytes).
        text.Append("    // Every name, ASCII: the objects' first, so that an object's number is its name's.\n")
            .Append("    private static ReadOnlySpan<byte> Names =>\n").Append("    [\n");
        var end = 0;
        var starts = new List<int>(names.Count + 1) { 0 };

        for (var i = 0; i < names.Count; i++)
        {
            Line(text, $"{Number(i)} {names[i]}", [.. names[i].Select(static c => (int)c)]);
            end += names[i].Length;
            starts.Add(end);
        }

        Refuse(end > ushort.MaxValue, $"{end} bytes of names do not fit 16-bit offsets.");
        text.Append("    ];\n\n")
            .Append("    // Where each name starts in Names, and where the last one ends.\n")
            .Append("    private static ReadOnlySpan<ushort> NameStarts =>\n").Append("    [\n");

        for (var i = 0; i < starts.Count; i += 16)
        {
            text.Append("        ").AppendJoin(", ", starts.Skip(i).Take(16).Select(Number)).Append(",\n");
        }

        text.Append("    ];\n\n");
    }

    private static void WriteObjects(StringBuilder text, CompiledModel model)
    {
        text.Append("    // Per object: first row (u16), rows (u8), flags (u8: 1 = array), first link (u16), first value (u16).\n")
            .Append("    private static ReadOnlySpan<byte> Objects =>\n").Append("    [\n");
        int row = 0, link = 0, value = 0;

        foreach (var obj in model.Objects)
        {
            Refuse(row > ushort.MaxValue || link > ushort.MaxValue || value > ushort.MaxValue, "the rows, links or values do not fit 16-bit offsets.");
            var bytes = new List<int>(ArlingtonLayout.ObjectSize);
            U16(bytes, row);
            bytes.Add(obj.Rows.Count);
            bytes.Add(obj.IsArray ? ArlingtonLayout.ObjectIsArray : 0);
            U16(bytes, link);
            U16(bytes, value);
            Line(text, obj.Name, bytes);
            row += obj.Rows.Count;
            link += obj.Rows.Sum(static r => r.Links.Count);
            value += obj.Rows.Sum(static r => r.Values.Count);
        }

        Refuse(link > ushort.MaxValue || value > ushort.MaxValue, "the links or values do not fit 16-bit offsets.");
        text.Append("    ];\n\n");
    }

    private static void WriteRows(StringBuilder text, CompiledModel model, List<string> names)
    {
        var ids = Index(names);
        text.Append("    // Per row: key (u16), types (u24), since (u8), deprecated in (u8), flags (u8), links (u8), values (u8).\n")
            .Append("    private static ReadOnlySpan<byte> Rows =>\n").Append("    [\n");

        foreach (var obj in model.Objects)
        {
            foreach (var row in obj.Rows)
            {
                Refuse(row.Links.Count > byte.MaxValue || row.Values.Count > byte.MaxValue, $"{obj.Name}/{row.Key} has more links or values than a byte counts.");
                var bytes = new List<int>(ArlingtonLayout.RowSize);
                U16(bytes, ids[row.Key]);
                var types = (uint)row.Types;
                bytes.Add((int)(types & 0xFF));
                bytes.Add((int)((types >> 8) & 0xFF));
                bytes.Add((int)((types >> 16) & 0xFF));
                bytes.Add(row.Since);
                bytes.Add(row.Deprecated);
                bytes.Add((byte)row.EncodedFlags);
                bytes.Add(row.Links.Count);
                bytes.Add(row.Values.Count);
                Line(text, RowName(obj, row), bytes);
            }
        }

        text.Append("    ];\n\n");
    }

    private static void WriteLinks(StringBuilder text, CompiledModel model, Dictionary<string, int> objectIds)
    {
        var sets = new Dictionary<string, int>(StringComparer.Ordinal);

        for (var i = 0; i < model.CandidateSets.Count; i++)
        {
            sets.Add(string.Join(',', model.CandidateSets[i].Members), i);
        }

        text.Append("    // Per link group: type (u8), then an object (u16), or a candidate set (u16, with 0x8000).\n")
            .Append("    private static ReadOnlySpan<byte> Links =>\n").Append("    [\n");

        foreach (var obj in model.Objects)
        {
            foreach (var row in obj.Rows.Where(static r => r.Links.Count > 0))
            {
                var bytes = new List<int>(ArlingtonLayout.LinkSize * row.Links.Count);

                foreach (var link in row.Links)
                {
                    bytes.Add((int)link.Type);
                    U16(bytes, link.Candidates.Count == 1
                        ? objectIds[link.Candidates[0]]
                        : ArlingtonLayout.CandidateSetFlag | sets[string.Join(',', link.Candidates)]);
                }

                Line(text, RowName(obj, row), bytes);
            }
        }

        text.Append("    ];\n\n");
    }

    private static void WriteCandidateSets(StringBuilder text, CompiledModel model, List<string> names, Dictionary<string, int> objectIds)
    {
        var ids = Index(names);
        text.Append("    // Per candidate set: first member (u16), members (u8), key telling its arrays apart (u16), key telling\n")
            .Append("    // its other candidates apart (u16), each a name, or 0xFFFF.\n")
            .Append("    private static ReadOnlySpan<byte> CandidateSets =>\n").Append("    [\n");
        var member = 0;

        for (var i = 0; i < model.CandidateSets.Count; i++)
        {
            var set = model.CandidateSets[i];
            Refuse(set.Members.Count > byte.MaxValue || member > ushort.MaxValue, "a candidate set does not fit its record.");
            var bytes = new List<int>(ArlingtonLayout.SetSize);
            U16(bytes, member);
            bytes.Add(set.Members.Count);
            U16(bytes, set.ArrayPlan is null ? ArlingtonLayout.NoPlan : ids[set.ArrayPlan]);
            U16(bytes, set.OtherPlan is null ? ArlingtonLayout.NoPlan : ids[set.OtherPlan]);
            Line(text, $"{Number(i)}: {set.ArrayPlan ?? "-"}, {set.OtherPlan ?? "-"}", bytes);
            member += set.Members.Count;
        }

        text.Append("    ];\n\n")
            .Append("    private static ReadOnlySpan<ushort> SetMembers =>\n").Append("    [\n");

        for (var i = 0; i < model.CandidateSets.Count; i++)
        {
            var set = model.CandidateSets[i];
            Line(text, $"{Number(i)}: {string.Join(", ", set.Members)}", [.. set.Members.Select(m => objectIds[m])]);
        }

        text.Append("    ];\n\n");
    }

    private static void WriteValues(StringBuilder text, CompiledModel model, List<string> names)
    {
        var ids = Index(names);
        text.Append("    // Per plain value: the value (u16, a name), its type (u8).\n")
            .Append("    private static ReadOnlySpan<byte> Values =>\n").Append("    [\n");

        foreach (var obj in model.Objects)
        {
            foreach (var row in obj.Rows.Where(static r => r.Values.Count > 0))
            {
                var bytes = new List<int>(ArlingtonLayout.ValueSize * row.Values.Count);

                foreach (var value in row.Values)
                {
                    U16(bytes, ids[value.Text]);
                    bytes.Add((int)value.Type);
                }

                Line(text, RowName(obj, row), bytes);
            }
        }

        text.Append("    ];\n\n");
    }

    private static void WriteExtras(StringBuilder text, CompiledModel model)
    {
        text.Append("    // Per row with extras, in order of rows: the row (u16), its overrides (u8), and the versions a\n")
            .Append("    // version-only requirement holds in, from (u8) included to before (u8) excluded.\n")
            .Append("    private static ReadOnlySpan<byte> Extras =>\n").Append("    [\n");
        var index = 0;

        foreach (var obj in model.Objects)
        {
            foreach (var row in obj.Rows)
            {
                if (row.HasExtras)
                {
                    var bytes = new List<int>(ArlingtonLayout.ExtraSize);
                    U16(bytes, index);
                    bytes.Add((byte)row.Overrides);
                    bytes.Add(row.Requirement == ArlingtonRequirement.InVersions ? row.RequiredFrom : ArlingtonVersion.None);
                    bytes.Add(row.Requirement == ArlingtonRequirement.InVersions ? row.RequiredBefore : ArlingtonVersion.Unbounded);
                    Line(text, RowName(obj, row), bytes);
                }

                index++;
            }
        }

        text.Append("    ];\n");
    }

    private static string RowName(CompiledObject obj, CompiledRow row) =>
        row.Edited ? $"{obj.Name}/{row.Key}, edited" : $"{obj.Name}/{row.Key}";

    private static Dictionary<string, int> Index(List<string> names)
    {
        var ids = new Dictionary<string, int>(names.Count, StringComparer.Ordinal);

        for (var i = 0; i < names.Count; i++)
        {
            ids.Add(names[i], i);
        }

        return ids;
    }

    private static void Line(StringBuilder text, string comment, List<int> bytes)
    {
        Refuse(comment.Contains("*/", StringComparison.Ordinal), $"'{comment}' would end its comment early.");
        text.Append("        /* ").Append(comment).Append(" */ ").AppendJoin(", ", bytes.Select(Number)).Append(",\n");
    }

    private static void U16(List<int> bytes, int value)
    {
        bytes.Add(value & 0xFF);
        bytes.Add((value >> 8) & 0xFF);
    }

    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);

    private static void Refuse(bool condition, string message)
    {
        if (condition)
        {
            throw new InvalidDataException($"The tables cannot hold the model: {message}");
        }
    }
}
